spring:
  main:
    banner-mode: OFF
  datasource:
    url: ${ACCOUNTING_DATABASE_URL}
    username: ${ACCOUNTING_DATABASE_USERNAME}
    password: ${ACCOUNTING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    baseline-on-migrate: true

server:
  port: 8881